[package]
name = "crashcart"
version = "0.1.0"
edition = "2021"

[dependencies]
openssh = {version="0.10.4", features=["process-mux", "native-mux"]}
rerun = "0.17.0"
tokio = {version = "1.39.2", features=["full"]}
